import { cn } from "@/lib/utils"
import "./globals.css"
import { Inter as FontSans } from "next/font/google"
import { Metadata } from "next"
import { Button } from "@/components/ui/button"
import PageHeader from "@/components/page-header"



export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <PageHeader></PageHeader>
        <div className="pt-2">
          {children}        
        </div>
      </body>
    </html>
  )
}
